name: project_CSE
channels:
  - defaults
dependencies:
  - nest-asyncio=1.4.3
  - wcwidth=0.2.5
  - six=1.15.0
  - numpy-base=1.19.2
  - requests=2.25.0
  - ipython_genutils=0.2.0
  - entrypoints=0.3
  - send2trash=1.5.0
  - libffi=3.3
  - pytz=2020.4
  - decorator=4.4.2
  - ncurses=6.2
  - backports=1.0
  - nbconvert=6.0.7
  - pip=20.3
  - markupsafe=1.1.1
  - _libgcc_mutex=0.1
  - cffi=1.14.4
  - jsonschema=3.2.0
  - prometheus_client=0.9.0
  - tzdata=2020d
  - defusedxml=0.6.0
  - terminado=0.9.1
  - tk=8.6.10
  - webencodings=0.5.1
  - pylint=2.6.0
  - wheel=0.35.1
  - backcall=0.2.0
  - ipython=7.19.0
  - pygments=2.7.2
  - wrapt=1.11.2
  - pycparser=2.20
  - cryptography=3.2.1
  - libsodium=1.0.18
  - altair=4.1.0
  - jupyterlab_server=1.2.0
  - testpath=0.4.4
  - libedit=3.1.20191231
  - astroid=2.4.2
  - jupyter_server=1.0.7
  - nbclient=0.5.1
  - certifi
  - pandoc=2.11.2
  - sqlite=3.33.0
  - pyopenssl=20.0.0
  - pexpect=4.8.0
  - pyparsing=2.4.7
  - mkl=2020.2
  - chardet=3.0.4
  - toml=0.10.1
  - nbformat=5.0.8
  - traitlets=5.0.5
  - pyzmq=20.0.0
  - blas=1.0
  - mccabe=0.6.1
  - mkl-service=2.3.0
  - pyrsistent=0.17.3
  - numpy=1.19.2
  - bleach=3.2.1
  - python_abi=3.8
  - importlib-metadata=3.1.0
  - json5=0.9.5
  - idna=2.10
  - ipykernel=5.3.4
  - brotlipy=0.7.0
  - mkl_random=1.1.1
  - zipp=3.4.0
  - jupyter_client=6.1.7
  - prompt-toolkit=3.0.8
  - lazy-object-proxy=1.4.3
  - mkl_fft=1.2.0
  - toolz=0.11.1
  - parso=0.7.1
  - urllib3=1.25.11
  - zeromq=4.3.3
  - packaging=20.4
  - mistune=0.8.4
  - vega_datasets=0.9.0
  - attrs=20.3.0
  - jupyterlab=2.2.9
  - xz=5.2.5
  - jinja2=2.11.2
  - readline=8.0
  - python-dateutil=2.8.1
  - ptyprocess=0.6.0
  - python=3.8.5
  - zlib=1.2.11
  - async_generator=1.10
  - setuptools=50.3.1
  - pandas=1.1.3
  - openssl
  - voila=0.2.4
  - pandocfilters=1.4.2
  - plotly=4.13.0
  - jupyterlab_pygments=0.1.2
  - intel-openmp=2020.2
  - jupyter_core=4.7.0
  - backports.functools_lru_cache=1.6.1
  - isort=5.6.4
  - notebook=6.1.5
  - pickleshare=0.7.5
  - argon2-cffi=20.1.0
  - jedi=0.17.2
  - importlib_metadata=3.1.0
  - retrying=1.3.3
  - pysocks=1.7.1
  - tornado=6.1
  - ca-certificates
  - dash
prefix: /Users/zrand/opt/miniconda3/envs/project_CSE
